### 모듈 로드

In [141]:
import pandas as pd

In [142]:
df1 = pd.read_csv('D:\Git\giteuk_plus\Data\Rawdata/cluster.csv',encoding='cp949')
df2 = pd.read_csv('D:\Git\giteuk_plus\Data\Preprocessing/활성화지표_추가본.csv',encoding='cp949')

In [143]:
p5 = df1.자치구.str.split(' ')
p5 = p5.apply(lambda x: pd.Series(x))
p5 = p5.rename(columns={1:'자치구'})
df1 = df1.drop(['자치구'], axis=1)
df1 = pd.concat([df1,p5.loc[:,'자치구']],axis=1)

In [144]:
df1

,시도명,행정동명,행정동코드,행정기관코드,과거대비인구변화(%),최근인구변화(연속감소년수),과거대비사업체변화(%),최근사업체변화(연속감소년수),노후건축물비율(%),재생도시,가구당인구수,자치구
0,서울특별시,사직동,1101053.0,1111053000,-13.703589,2,0.338696,1,73.636364,1.0,2.07,종로구
1,서울특별시,삼청동,1101054.0,1111054000,-71.395349,3,-2.691790,1,77.192982,1.0,1.98,종로구
2,서울특별시,부암동,1101055.0,1111055000,-28.333333,5,4.251386,1,75.547703,0.0,2.35,종로구
3,서울특별시,평창동,1101056.0,1111056000,-4.272303,4,2.092050,0,71.133568,0.0,2.48,종로구
4,서울특별시,무악동,1101057.0,1111057000,-37.690513,3,-15.185185,4,54.545455,0.0,2.74,종로구
...,...,...,...,...,...,...,...,...,...,...,...,...
419,서울특별시,둔촌1동,1125070.0,1174069000,-99.865471,5,-94.910180,5,70.370370,0.0,1.63,강동구
420,서울특별시,둔촌2동,1125071.0,1174070000,-14.202147,3,-5.244253,3,63.047138,0.0,2.48,강동구
421,서울특별시,암사1동,1125072.0,1174057000,-16.278442,3,-3.260870,2,62.685851,1.0,2.27,강동구
422,서울특별시,천호2동,1125073.0,1174061000,-6.641188,3,-8.824392,1,74.177313,0.0,2.00,강동구
423,서울특별시,길동,1125074.0,1174068500,-10.596548,4,-2.389974,1,63.755679,0.0,2.26,강동구

In [145]:
df1 = df1[['자치구', '행정동명', '재생도시']]

In [146]:
df1

     자치구  행정동명  재생도시
0    종로구   사직동   1.0
1    종로구   삼청동   1.0
2    종로구   부암동   0.0
3    종로구   평창동   0.0
4    종로구   무악동   0.0
..   ...   ...   ...
419  강동구  둔촌1동   0.0
420  강동구  둔촌2동   0.0
421  강동구  암사1동   1.0
422  강동구  천호2동   0.0
423  강동구    길동   0.0

[424 rows x 3 columns]

In [147]:
df2

,자치구,행정동명,행정동코드,과거대비인구변화(%),최근인구변화(연속감소년수),과거대비사업체변화(%),최근사업체변화(연속감소년수),노후건축물비율(%),노인인구비율,기초생활 대상자 비율
0,종로구,사직동,1111053000,-13.703589,2,0.338696,1,73.636364,0.187946,0.011116
1,종로구,삼청동,1111054000,-71.395349,3,-2.691790,1,77.192982,0.231695,0.010657
2,종로구,부암동,1111055000,-28.333333,5,4.251386,1,75.547703,0.177973,0.011033
3,종로구,평창동,1111056000,-4.272303,4,2.092050,0,71.133568,0.182865,0.005220
4,종로구,무악동,1111057000,-37.690513,3,-15.185185,4,54.545455,0.169926,0.013734
...,...,...,...,...,...,...,...,...,...,...
419,강동구,성내3동,1174066000,-14.897188,5,-0.754549,1,53.799392,0.156213,0.020387
420,강동구,둔촌2동,1174070000,-14.202147,3,-5.244253,3,63.047138,0.156552,0.014803
421,강동구,암사1동,1174057000,-16.278442,3,-3.260870,2,62.685851,0.166956,0.036218
422,강동구,천호2동,1174061000,-6.641188,3,-8.824392,1,74.177313,0.169329,0.040822
423,강동구,길동,1174068500,-10.596548,4,-2.389974,1,63.755679,0.163843,0.023107

In [148]:
df2 =df2[['자치구','행정동명','행정동코드']]

In [149]:
result = pd.merge(df1,df2)[['행정동코드','재생도시']]

In [153]:
result.to_csv('../Data/Preprocessing/재생도시.csv',encoding='utf-8',index=False)