## 라이브러리 import

In [1]:
import pandas as pd  #데이터 분석 라이브러리
import numpy as np # 계산 라이브러리

import matplotlib as mpl # 그래프 라이브러리
import matplotlib.pyplot as plt #pyplot 그래프 라이브러리
import matplotlib.font_manager as fm  #그래프 폰트 라이브러리
from pandas import Series, DataFrame

plt.rc("font", family="Malgun Gothic") #폰트 맑은 고딕 적용

## 데이터 불러오기

In [2]:
kmeans = pd.read_csv('../Data/Result/kmeans.csv',encoding='cp949') #kmeans 타겟 클러스터 데이터
kmedoids = pd.read_csv('../Data/Result/k-medoids.csv',encoding='cp949') #kmedoids 타겟 클러스터 데이터
gmm = pd.read_csv('../Data/Result/gmm.csv',encoding='cp949') #gmm타겟 클러스터 데이터
df = pd.read_csv('../Data/Preprocessing/활성화지표_추가본.csv',encoding='cp949') #전체 데이터
re_city = pd.read_csv('../Data/Preprocessing/재생도시.csv') #재생도시 데이터

In [3]:
kmeans

,과거대비인구변화(%),최근인구변화(연속감소년수),과거대비사업체변화(%),최근사업체변화(연속감소년수),노후건축물비율(%),노인인구비율,기초생활 대상자 비율,행정동코드
0,-71.395349,3,-2.691790,1,77.192982,0.231695,0.014094,1111054000
1,-37.690513,3,-15.185185,4,54.545455,0.169926,0.018040,1111057000
2,-57.091410,5,-0.800000,1,75.487013,0.212087,0.015844,1111060000
3,-64.354556,3,-6.558862,5,87.413555,0.197843,0.051450,1111063000
4,-58.991001,5,-11.170213,2,81.572052,0.174454,0.032918,1111064000
...,...,...,...,...,...,...,...,...
92,-50.225033,5,-13.950073,4,90.035273,0.192252,0.036613,1171051000
93,-44.188005,4,-33.160622,4,82.733813,0.180393,0.040973,1171053200
94,-50.376510,2,-10.462472,5,53.546911,0.140215,0.018449,1171064100
95,-37.813261,4,0.442478,1,50.000000,0.137405,0.006786,1174059000
96,-35.860909,3,-8.489526,3,73.132724,0.169593,0.033309,1174065000

In [4]:
kmedoids

,과거대비인구변화(%),최근인구변화(연속감소년수),과거대비사업체변화(%),최근사업체변화(연속감소년수),노후건축물비율(%),노인인구비율,기초생활 대상자 비율,행정동코드
0,-71.395349,3,-2.691790,1,77.192982,0.231695,0.014094,1111054000
1,-57.091410,5,-0.800000,1,75.487013,0.212087,0.015844,1111060000
2,-64.354556,3,-6.558862,5,87.413555,0.197843,0.051450,1111063000
3,-58.991001,5,-11.170213,2,81.572052,0.174454,0.032918,1111064000
4,-60.099208,5,-9.995818,2,91.774383,0.212609,0.076123,1111067000
...,...,...,...,...,...,...,...,...
90,-44.188005,4,-33.160622,4,82.733813,0.180393,0.040973,1171053200
91,-26.740168,5,-1.272984,1,82.880435,0.209503,0.077904,1171054000
92,-31.081230,5,-6.329114,4,82.834331,0.205031,0.072164,1171055000
93,-24.628619,5,-7.034221,2,83.018868,0.141119,0.000649,1171056600
94,-28.072692,4,-4.522613,3,98.275862,0.212764,0.000909,1171072000

In [5]:
gmm

,과거대비인구변화(%),최근인구변화(연속감소년수),과거대비사업체변화(%),최근사업체변화(연속감소년수),노후건축물비율(%),노인인구비율,기초생활 대상자 비율,행정동코드
0,-71.395349,3,-2.691790,1,77.192982,0.231695,0.010657,1111054000
1,-37.690513,3,-15.185185,4,54.545455,0.169926,0.013734,1111057000
2,-57.091410,5,-0.800000,1,75.487013,0.212087,0.012449,1111060000
3,-10.256026,4,-3.794240,4,75.576037,0.235677,0.091027,1111061500
4,-60.099208,5,-9.995818,2,91.774383,0.212609,0.066566,1111067000
5,-49.221646,2,-16.137566,4,90.170512,0.269585,0.080945,1114054000
6,-37.332589,3,-18.294574,5,90.266106,0.191864,0.025561,1114059000
7,-64.764320,2,-12.184664,4,94.223827,0.266904,0.063549,1114060500
8,-37.757063,5,-7.171776,1,88.413098,0.202316,0.148472,1117053000
9,-16.546577,1,-21.651786,5,63.434022,0.141294,0.008232,1117058000
10,-53.217680,4,-10.040706,1,81.346841,0.177490,0.018990,1117066000
11,-35.618795,5,14.190317,0,83.822297,0.140268,0.014194,1120066000
12,-53.598114,5,-12.265084,2,88.451160,0.168500,0.052106,1120079000
13,-16.409513,5,-6.759318,5,89.123867,0.258320,0.069792,1123070500
14,-42.260503,5,-20.799408,4,89.893617,0.155011,0.024475,1123074000
15,-38.042701,4,-25.418060,4,77.196885,0.145829,0.032945,1126055000
16,-16.016399,3,-9.674185,2,83.068783,0.191347,0.069919,1126061000
17,-35.651936,3,0.782998,0,76.416185,0.188371,0.071682,1126066000
18,-33.289194,5,-21.405049,4,83.194444,0.181280,0.055015,1129076000
19,-53.440033,4,-36.621622,5,91.500000,0.221253,0.046292,1129077000
20,-38.284953,5,-9.188034,2,86.681465,0.238636,0.070358,1130560300
21,-31.675361,5,-4.950495,2,71.848739,0.261801,0.098722,1130560800
22,-21.462392,5,-23.106061,3,79.148753,0.197559,0.047450,1130553400
23,-42.742366,5,5.783457,2,80.036052,0.196013,0.039211,1130553500
24,-11.058131,4,-10.709046,5,89.029203,0.220767,0.048330,1130555500
25,-54.753835,5,-5.229358,1,71.744681,0.195713,0.035608,1132067000
26,-34.055939,5,-10.144928,3,77.088036,0.208909,0.071802,1132070000
27,-13.216176,1,-22.734761,2,60.879121,0.206084,0.081695,1135057000
28,-19.533397,2,0.000000,0,60.424710,0.155444,0.075630,1135061100
29,-19.289054,5,-0.703400,1,63.270777,0.190680,0.064765,1135062400
30,-31.643887,4,-28.940986,4,89.918256,0.222888,0.066363,1135066500
31,-17.604891,5,1.239276,1,79.120879,0.202889,0.087787,1135062500
32,-65.411820,4,-41.530055,5,81.382979,0.180494,0.034997,1138065000
33,-33.370127,2,-15.310345,2,52.459016,0.133263,0.010532,1141069000
34,-25.230451,4,13.449132,1,70.023148,0.145241,0.025140,1144068000
35,-36.318723,5,-9.358974,1,86.043614,0.185155,0.066082,1147058000
36,-23.014966,5,-4.640272,2,67.839196,0.205243,0.128680,1150053500
37,-52.882904,4,-7.755102,1,62.181818,0.151973,0.030224,1150055000
38,-40.133254,5,-1.478743,2,75.630252,0.264601,0.165890,1150060400
39,-32.945001,5,-0.839161,1,78.333333,0.228967,0.105820,1150060500
40,-28.411095,5,-1.774194,2,72.907489,0.210671,0.066251,1150064100
41,-19.941327,5,17.117117,0,52.737752,0.183143,0.042006,1154568000
42,-40.898711,2,-25.583658,5,88.372093,0.170850,0.033009,1156065000
43,-54.382555,4,-35.067437,4,89.122373,0.171111,0.039232,1156066000
44,-61.490638,4,-23.760684,4,86.467662,0.165893,0.032650,1156067000
45,-55.506231,5,-4.359198,1,72.407733,0.168581,0.018405,1156068000
46,-50.416130,5,-2.533883,1,94.201313,0.199600,0.055802,1159052000
47,-14.294495,1,-4.589788,5,65.384615,0.155848,0.023443,1159062000
48,-60.356500,2,-6.984668,1,64.387211,0.179670,0.026988,1159065000
49,-44.165802,3,-10.913140,2,60.029283,0.145591,0.027610,1162072500
50,-44.285245,2,11.796009,2,60.566038,0.119645,0.003865,1165052000
51,-50.871792,2,0.379816,0,55.145119,0.162821,0.013118,1165060000
52,-39.953709,5,-16.693679,4,70.486656,0.175535,0.009105,1168051000
53,-82.499049,5,-64.542936,3,74.074074,0.234933,0.017841,1168066000
54,-35.470532,5,-8.098988,2,87.234043,0.199848,0.070070,1168073000
55,-24.458639,2,-13.527397,2,59.440559,0.178723,0.050652,1168074000
56,-36.396428,3,-8.381689,4,68.949772,0.288254,0.158246,1168075000
57,-39.658110,3,-24.008811,3,64.174455,0.140916,0.005786,1168067000
58,-44.188005,4,-33.160622,4,82.733813,0.180393,0.029798,1171053200
59,-50.376510,2,-10.462472,5,53.546911,0.140215,0.012316,1171064100

In [6]:
re_city

          행정동코드  재생도시
0    1111053000   1.0
1    1111054000   1.0
2    1111055000   0.0
3    1111056000   0.0
4    1111057000   0.0
..          ...   ...
418  1174066000   0.0
419  1174070000   0.0
420  1174057000   1.0
421  1174061000   0.0
422  1174068500   0.0

[423 rows x 2 columns]

In [7]:
raw_data = df[['자치구','행정동명','과거대비인구변화(%)','최근인구변화(연속감소년수)','과거대비사업체변화(%)','최근사업체변화(연속감소년수)','노후건축물비율(%)', '노인인구비율', 
                  '기초생활 대상자 비율','행정동코드']]

## 세 클러스터에서 겹치는 데이터만 추출

In [8]:
#각 모델에서 행정동 코드만 추출
k_mean = kmeans['행정동코드'] 
k_medoids = kmedoids['행정동코드']
g_mm = gmm['행정동코드']

#set 하기 위해 값만 뽑아옴
km_val = k_mean.values
kd_val = k_medoids.values
g_val = g_mm.values

#set진행
km = set(km_val)
kd= set(kd_val)
g = set(g_val)

In [9]:
final = km&kd&g #set을 이용해 겹치는 데이터 추출

In [10]:
final_df = pd.DataFrame(final).rename(columns={0:'행정동코드'}) #결과물 dataframe형태로 바꾸기

In [11]:
final_df

         행정동코드
0   1135066500
1   1129077000
2   1117066000
3   1171053200
4   1120079000
5   1130553500
6   1111060000
7   1129076000
8   1156068000
9   1159065000
10  1168073000
11  1130560300
12  1111054000
13  1156067000
14  1168051000
15  1132067000
16  1117053000
17  1168066000
18  1123074000
19  1147058000
20  1156066000
21  1114060500
22  1126055000
23  1159052000
24  1114059000
25  1138065000
26  1156065000
27  1114054000
28  1132070000
29  1150060400
30  1111067000

## 행정동 코드를 이용해 타겟 데이터의 정보 추출

In [12]:
final_target = pd.merge(final_df,raw_data,on=['행정동코드'],how='left')
final_target_all = pd.merge(final_target,re_city,on=['행정동코드'], how='left')

In [13]:
final_target_all

,행정동코드,자치구,행정동명,과거대비인구변화(%),최근인구변화(연속감소년수),과거대비사업체변화(%),최근사업체변화(연속감소년수),노후건축물비율(%),노인인구비율,기초생활 대상자 비율,재생도시
0,1135066500,노원구,상계3·4동,-31.643887,4,-28.940986,4,89.918256,0.222888,0.090605,0.0
1,1129077000,성북구,장위2동,-53.440033,4,-36.621622,5,91.500000,0.221253,0.067843,1.0
2,1117066000,용산구,이태원2동,-53.217680,4,-10.040706,1,81.346841,0.177490,0.026216,0.0
3,1171053200,송파구,거여2동,-44.188005,4,-33.160622,4,82.733813,0.180393,0.040973,0.0
4,1120079000,성동구,용답동,-53.598114,5,-12.265084,2,88.451160,0.168500,0.067353,1.0
5,1130553500,강북구,미아동,-42.742366,5,5.783457,2,80.036052,0.196013,0.049905,0.0
6,1111060000,종로구,가회동,-57.091410,5,-0.800000,1,75.487013,0.212087,0.015844,1.0
7,1129076000,성북구,장위1동,-33.289194,5,-21.405049,4,83.194444,0.181280,0.091056,1.0
8,1156068000,영등포구,신길6동,-55.506231,5,-4.359198,1,72.407733,0.168581,0.024120,0.0
9,1159065000,동작구,사당4동,-60.356500,2,-6.984668,1,64.387211,0.179670,0.037126,1.0
10,1168073000,강남구,일원1동,-35.470532,5,-8.098988,2,87.234043,0.199848,0.102230,0.0
11,1130560300,강북구,번2동,-38.284953,5,-9.188034,2,86.681465,0.238636,0.103542,0.0
12,1111054000,종로구,삼청동,-71.395349,3,-2.691790,1,77.192982,0.231695,0.014094,1.0
13,1156067000,영등포구,신길5동,-61.490638,4,-23.760684,4,86.467662,0.165893,0.043054,0.0
14,1168051000,강남구,신사동,-39.953709,5,-16.693679,4,70.486656,0.175535,0.011825,0.0
15,1132067000,도봉구,쌍문2동,-54.753835,5,-5.229358,1,71.744681,0.195713,0.051015,0.0
16,1117053000,용산구,남영동,-37.757063,5,-7.171776,1,88.413098,0.202316,0.155865,0.0
17,1168066000,강남구,개포1동,-82.499049,5,-64.542936,3,74.074074,0.234933,0.022789,0.0
18,1123074000,동대문구,이문1동,-42.260503,5,-20.799408,4,89.893617,0.155011,0.032775,0.0
19,1147058000,양천구,신월3동,-36.318723,5,-9.358974,1,86.043614,0.185155,0.089759,1.0
20,1156066000,영등포구,신길4동,-54.382555,4,-35.067437,4,89.122373,0.171111,0.052567,0.0
21,1114060500,중구,을지로동,-64.764320,2,-12.184664,4,94.223827,0.266904,0.065074,1.0
22,1126055000,중랑구,면목5동,-38.042701,4,-25.418060,4,77.196885,0.145829,0.049519,0.0
23,1159052000,동작구,노량진2동,-50.416130,5,-2.533883,1,94.201313,0.199600,0.073120,0.0
24,1114059000,중구,광희동,-37.332589,3,-18.294574,5,90.266106,0.191864,0.030081,1.0
25,1138065000,은평구,수색동,-65.411820,4,-41.530055,5,81.382979,0.180494,0.046456,0.0
26,1156065000,영등포구,신길3동,-40.898711,2,-25.583658,5,88.372093,0.170850,0.044344,0.0
27,1114054000,중구,회현동,-49.221646,2,-16.137566,4,90.170512,0.269585,0.085114,1.0
28,1132070000,도봉구,방학2동,-34.055939,5,-10.144928,3,77.088036,0.208909,0.108973,0.0
29,1150060400,강서구,가양2동,-40.133254,5,-1.478743,2,75.630252,0.264601,0.215245,0.0
30,1111067000,종로구,창신1동,-60.099208,5,-9.995818,2,91.774383,0.212609,0.076123,1.0

In [14]:
final_final_target = final_target_all[final_target_all['재생도시']==0.0] #현재 재생도시 진행중인곳은 대상에서 제외

In [15]:
final_final_target

,행정동코드,자치구,행정동명,과거대비인구변화(%),최근인구변화(연속감소년수),과거대비사업체변화(%),최근사업체변화(연속감소년수),노후건축물비율(%),노인인구비율,기초생활 대상자 비율,재생도시
0,1135066500,노원구,상계3·4동,-31.643887,4,-28.940986,4,89.918256,0.222888,0.090605,0.0
2,1117066000,용산구,이태원2동,-53.217680,4,-10.040706,1,81.346841,0.177490,0.026216,0.0
3,1171053200,송파구,거여2동,-44.188005,4,-33.160622,4,82.733813,0.180393,0.040973,0.0
5,1130553500,강북구,미아동,-42.742366,5,5.783457,2,80.036052,0.196013,0.049905,0.0
8,1156068000,영등포구,신길6동,-55.506231,5,-4.359198,1,72.407733,0.168581,0.024120,0.0
10,1168073000,강남구,일원1동,-35.470532,5,-8.098988,2,87.234043,0.199848,0.102230,0.0
11,1130560300,강북구,번2동,-38.284953,5,-9.188034,2,86.681465,0.238636,0.103542,0.0
13,1156067000,영등포구,신길5동,-61.490638,4,-23.760684,4,86.467662,0.165893,0.043054,0.0
14,1168051000,강남구,신사동,-39.953709,5,-16.693679,4,70.486656,0.175535,0.011825,0.0
15,1132067000,도봉구,쌍문2동,-54.753835,5,-5.229358,1,71.744681,0.195713,0.051015,0.0
16,1117053000,용산구,남영동,-37.757063,5,-7.171776,1,88.413098,0.202316,0.155865,0.0
17,1168066000,강남구,개포1동,-82.499049,5,-64.542936,3,74.074074,0.234933,0.022789,0.0
18,1123074000,동대문구,이문1동,-42.260503,5,-20.799408,4,89.893617,0.155011,0.032775,0.0
20,1156066000,영등포구,신길4동,-54.382555,4,-35.067437,4,89.122373,0.171111,0.052567,0.0
22,1126055000,중랑구,면목5동,-38.042701,4,-25.418060,4,77.196885,0.145829,0.049519,0.0
23,1159052000,동작구,노량진2동,-50.416130,5,-2.533883,1,94.201313,0.199600,0.073120,0.0
25,1138065000,은평구,수색동,-65.411820,4,-41.530055,5,81.382979,0.180494,0.046456,0.0
26,1156065000,영등포구,신길3동,-40.898711,2,-25.583658,5,88.372093,0.170850,0.044344,0.0
28,1132070000,도봉구,방학2동,-34.055939,5,-10.144928,3,77.088036,0.208909,0.108973,0.0
29,1150060400,강서구,가양2동,-40.133254,5,-1.478743,2,75.630252,0.264601,0.215245,0.0

In [16]:
final_final_target.to_csv('../Data/Result/final_target_cluster.csv',encoding='cp949',index=False)

## 타겟 클러스터 행정동 특성 도출

In [17]:
target_infor = final_target_all[['과거대비인구변화(%)','최근인구변화(연속감소년수)','과거대비사업체변화(%)','최근사업체변화(연속감소년수)','노후건축물비율(%)',
                                       '노인인구비율','기초생활 대상자 비율']] #타겟 클러스터 행정동 특성 변수 뽑기

In [18]:
target_infor

,과거대비인구변화(%),최근인구변화(연속감소년수),과거대비사업체변화(%),최근사업체변화(연속감소년수),노후건축물비율(%),노인인구비율,기초생활 대상자 비율
0,-31.643887,4,-28.940986,4,89.918256,0.222888,0.090605
1,-53.440033,4,-36.621622,5,91.500000,0.221253,0.067843
2,-53.217680,4,-10.040706,1,81.346841,0.177490,0.026216
3,-44.188005,4,-33.160622,4,82.733813,0.180393,0.040973
4,-53.598114,5,-12.265084,2,88.451160,0.168500,0.067353
5,-42.742366,5,5.783457,2,80.036052,0.196013,0.049905
6,-57.091410,5,-0.800000,1,75.487013,0.212087,0.015844
7,-33.289194,5,-21.405049,4,83.194444,0.181280,0.091056
8,-55.506231,5,-4.359198,1,72.407733,0.168581,0.024120
9,-60.356500,2,-6.984668,1,64.387211,0.179670,0.037126
10,-35.470532,5,-8.098988,2,87.234043,0.199848,0.102230
11,-38.284953,5,-9.188034,2,86.681465,0.238636,0.103542
12,-71.395349,3,-2.691790,1,77.192982,0.231695,0.014094
13,-61.490638,4,-23.760684,4,86.467662,0.165893,0.043054
14,-39.953709,5,-16.693679,4,70.486656,0.175535,0.011825
15,-54.753835,5,-5.229358,1,71.744681,0.195713,0.051015
16,-37.757063,5,-7.171776,1,88.413098,0.202316,0.155865
17,-82.499049,5,-64.542936,3,74.074074,0.234933,0.022789
18,-42.260503,5,-20.799408,4,89.893617,0.155011,0.032775
19,-36.318723,5,-9.358974,1,86.043614,0.185155,0.089759
20,-54.382555,4,-35.067437,4,89.122373,0.171111,0.052567
21,-64.764320,2,-12.184664,4,94.223827,0.266904,0.065074
22,-38.042701,4,-25.418060,4,77.196885,0.145829,0.049519
23,-50.416130,5,-2.533883,1,94.201313,0.199600,0.073120
24,-37.332589,3,-18.294574,5,90.266106,0.191864,0.030081
25,-65.411820,4,-41.530055,5,81.382979,0.180494,0.046456
26,-40.898711,2,-25.583658,5,88.372093,0.170850,0.044344
27,-49.221646,2,-16.137566,4,90.170512,0.269585,0.085114
28,-34.055939,5,-10.144928,3,77.088036,0.208909,0.108973
29,-40.133254,5,-1.478743,2,75.630252,0.264601,0.215245
30,-60.099208,5,-9.995818,2,91.774383,0.212609,0.076123

In [19]:
target_infor.iloc[:,1].count()

31

In [20]:
#각 변수별 평균
aad = []
for i in range(0,7):
        a  = target_infor.iloc[:,i].sum()/31
        aad.append(a)

In [21]:
aad

[-49.03279513773687,
 4.225806451612903,
 -16.603209354747264,
 2.806451612903226,
 83.1330056769075,
 0.19920153738694102,
 0.06401951069851868]

## 전체 집단 특성 도출(타겟 클러스터의 특성과 비교하기 위함)

In [22]:
raw_data = raw_data.drop(raw_data.index[275]) #항동 제거

In [23]:
total = raw_data[['과거대비인구변화(%)','최근인구변화(연속감소년수)','과거대비사업체변화(%)','최근사업체변화(연속감소년수)','노후건축물비율(%)','노인인구비율','기초생활 대상자 비율']]

In [24]:
total.iloc[:,1].count()

423

In [27]:
#각 변수별 평균
aad_total = []
for i in range(0,7):
        b  = total.iloc[:,i].sum()/423
        aad_total.append(b)

In [28]:
aad_total

[-19.482527157523638,
 3.5768321513002364,
 -5.0584467017419685,
 1.962174940898345,
 70.9393032992157,
 0.16205003356870465,
 0.037137855670399275]